interface ZAPLINK_TYPES
  public .


  interfaces ZAPLINK_KERNEL_TYPES .

  aliases BALLOG_OBJECT
    for ZAPLINK_KERNEL_TYPES~BALLOG_OBJECT .

  types TO_COMPONENT type ZAPLINK_KERNEL_TYPES=>TO_COMPONENT .
  types TO_CONTAINER type ZAPLINK_KERNEL_TYPES=>TO_CONTAINER .
  types TO_FILE type ZAPLINK_KERNEL_TYPES=>TO_FILE .
  types TO_GUI type ref to ZAPLINK_GUI .
  types TO_LIST type ZAPLINK_KERNEL_TYPES=>TO_LIST .
  types TO_MSG_COLL type ZAPLINK_KERNEL_TYPES=>TO_MSG_COLL .
  types TO_OPTIONS type ZAPLINK_KERNEL_TYPES=>TO_OPTIONS .
  types TO_OPT_DEVCLASS type ZAPLINK_KERNEL_TYPES=>TO_OPT_DEVCLASS .
  types TO_RAW type ZAPLINK_KERNEL_TYPES=>TO_RAW .
endinterface.
